#!/bin/bash +x
echo "remove auto update an replace satellites.xml...."
rm -f /usr/bin/icam_autoupdate
rm -f /etc/init.d/bouquet_autoupdate
curl -sko /etc/enigma2/lamedb https://i.tv-lounge.eu/ot_tune/settings/lamedb
curl -sko /etc/tuxbox/satellites.xml https://i.tv-lounge.eu/ot_tune/settings/satellites.xml
echo -e "\e[32m all done ...\e[0m"
  echo -e "\e[33m ... doing restart \e[0m"
  sleep 3
  reboot
